config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"



 root :to => 'pages#home'
 require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users, :controllers => { :registrations => :registrations }
  resources :seeds, only: [:index, :new, :create, :update, :show], shallow: true do
    member do
      patch :update_delivery_costs
      put :update_delivery_costs
    end
    resources :picks, only: [:index, :edit, :show, :create, :update, :destroy] do
      member do
        patch :update_card
        put :update_card
      end
      resources :exchanges, only: [:create, :update]
      resources :payments, only: [:new, :create, :destroy]
    end
    resources :signal_seeds, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [ :show, :edit, :update] do
    member do
        patch :update_address
        put :update_address
        patch :update_paiement
        put :update_paiement
        patch :update_civil
        put :update_civil
      end
  end
  resources :addresses, only: [:create, :update]
  resources :campaigns, only: [:update]


  get 'signaled', to: 'campaigns#signaled'
  get 'pending', to: 'campaigns#pending'
  get 'success', to: 'campaigns#success'
  get 'fail', to: 'campaigns#fail'

  get 'message', to: 'campaigns#message'


  get 'admin', to: 'seeds#admin'
  get 'publish_seed', to: 'seeds#publish_seed'
  get 'newest', to: 'seeds#newest'
  get 'popular', to: 'seeds#popular'
  get 'last_day', to: 'seeds#last_day'

  get 'my_picks', to: 'picks#my_picks'
  get 'pick_history', to: 'picks#pick_history'

  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'contact', to: 'pages#contact'
  get 'mentions_legales', to: 'pages#mentions_legales'
  get 'cgu', to: 'pages#cgu'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :pseudo, uniqueness: true
   validates :pseudo, presence: true
   # validates :insta, url: true
   # validates :facebook, url: true
   # validates :youtube, url: true
   validates :terms_of_service, acceptance: { message: 'Merci de valider' }

   has_many :seeds
   has_many :picks, dependent: :destroy
   has_many :exchanges
   has_many :addresses, dependent: :destroy
   accepts_nested_attributes_for :addresses
   has_attachment :photo
   has_many :user_preferences
   has_many :signal_seed

  after_create :send_welcome_email
  after_create :subscribe_to_newsletter

  extend FriendlyId
  friendly_id :pseudo, use: :slugged


  def has_photo?
    self.photo?
  end

  def has_picked?(seed)
    seed.picks.where(user: self).any?
  end

  def has_signaled?(seed)
      seed.signal_seed.where(user: self).any?
  end


  def mini_bio?
    !self.mini_bio.blank?
  end

  def facebook?
    !self.facebook.blank?
  end

  def insta?
    !self.insta.blank?
  end

  def youtube?
    !self.youtube.blank?
  end

  def twitter?
    !self.twitter.blank?
  end

  def social_links?
    facebook? || insta? || youtube? || twitter?
  end

  def social_card?
    mini_bio? || social_links? || seeder_other_seeds?
  end

  def seeder_other_seeds?
    self.seeds.count - 1 > 0
  end

  def seeder_other_seeds_list(seed)
    self.seeds.reject{|current| current == seed}
  end


  private

  def send_welcome_email
    # UserMailer.welcome(self).deliver_now
    UserMailer.welcome(self.id).deliver_later(wait_until: 1.day.from_now)

  end

  def subscribe_to_newsletter
    AddUserToMarketingListJob.perform_later(self.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_sample, only: [:show, :update]


  def show
    @user = User.friendly.find(params[:id])
    unless @user.customer_id.blank?
      @addresses = @user.addresses.first
      @customer_infos = Stripe::Customer.retrieve(@user.customer_id).sources.data[0]
    end
    authorize @user
  end

  def update
    @user = User.friendly.find(params[:id])
    @user.slug = @user.pseudo
    authorize @user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :show
    end
  end

  def update_civil
    @user = User.friendly.find(params[:id])
    authorize @user
    if @user.update(civil_params)
      respond_to do |format|
        format.html {redirect_to user_path(@user)}
        format.js
      end
    end
  end

  def update_address
    @user = User.friendly.find(params[:id])
    @addresses = @user.addresses.first
    authorize @user
    if @addresses.update(address_params)
      respond_to do |format|
        format.html {redirect_to user_path(@user)}
        format.js
      end
    end
  end

  def update_paiement
    @user = User.friendly.find(params[:id])
    authorize @user
    cu = Stripe::Customer.retrieve("#{@user.customer_id}")
    card = params[:stripeToken]
    cu.sources.create(source: card)
    card = Stripe::Token.retrieve(card)["card"]
    cu.default_source = card
    cu.save
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:photo, :insta, :youtube, :facebook, :twitter, :mini_bio, :pseudo)
  end

  def address_params
    params.require(:address).permit(:first_name, :last_name, :street, :zip_code, :city, :address_complement, :phone_number)
  end

  def civil_params
    params.require(:user).permit(:sex, :date_of_birth, :email)
  end



end

app/views/users/_card-infos.html.erb
<div class="title-and-data">
  <div class="title">Carte:</div>
  <div class="data">
    <div class="stripe-block"><%= customer_infos["brand"]%></div>
    <div class="stripe-block">
      **** **** **** <%= customer_infos["last4"] %>
    </div>
    <div class="stripe-block">
      <%= customer_infos["exp_month"]%>/<%= customer_infos["exp_year"] %>
    </div>
  </div>
</div>

app/views/users/_civil.html.erb
<div class="title-and-data">
  <div class="title">Sexe:</div>
  <div class="data <%= 'blank' if user.sex.blank? %>">
    <% if user.sex.blank? %>
      <%= "Non renseigné" %>
    <% elsif  user.sex == "man"%>
      <%= "Homme" %>
    <% else %>
      <%= "Femme" %>
    <% end %>
  </div>
</div>
<div class="title-and-data">
  <div class="title">Date de naissance:</div>
  <div class="data <%= 'blank' if user.date_of_birth.blank? %>"><%= user.date_of_birth.blank? ? "Non renseignée" : user.date_of_birth.strftime("%d/%m/%y") %>
  </div>
</div>
<div class="title-and-data">
  <div class="title">Email:</div>
  <div class="data"><%= user.email %></div>
</div>

app/views/users/_livraison.html.erb
<div class="title-and-data">
  <%= addresses.first_name %>
  <%= addresses.last_name %>
</div>
<div class="title-and-data">
  <%= addresses.street %>
</div>
<div class="title-and-data">
  <%= addresses.zip_code %> <%= addresses.city %>
</div>
<div class="title-and-data">
  <div class="title">Complément d'adresse:</div>
  <div class="data <%= 'blank' if addresses.address_complement.blank? %>"><%= addresses.address_complement.blank? ? "Non renseigné" : addresses.address_complement %>
  </div>
</div>
<div class="title-and-data">
  <div class="title">Téléphone:</div>
  <div class="data <%= 'blank' if addresses.phone_number.blank? %>"><%= addresses.phone_number.blank? ? "Non renseigné" : addresses.phone_number %>
  </div>
</div>

app/views/users/my_picks.html.erb
<div class="page-container">
  <div class="pick-feed">
    <%if @picks.any? %>
      <div class="pick-presentation">
        <h2>Vos picks</h2>
        <% @picks.each do |pick| %>
          <div class="pick-iterate id-<%= pick.id%>">
          <%= render "users/pick-history", pick: pick %>
          </div>
          <% if pick.seed.ongoing? %>
            <div class="pick-modal">
            <!-- Modal -->
              <div class="modal fade" id="myPick-<%= pick.id%>" role="dialog">
                <div class="modal-dialog modal">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title"><%= pick.seed.title %> </h4>
                    </div>
                    <div class="modal-body">
                      <h3>Modifier votre prix </h3>
                      <div class="pick-modal">
                        <%= render "picks/edit-form", seed: pick.seed, pick: pick %>
                      </div>
                    </div>
                    <div class="modal-footer hidden">
                      <button type="button" id="close-modal-<%= pick.id%>" class="btn btn-default text-center" data-dismiss="modal">Retour</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="pick-modal">
            <!-- Modal -->
              <div class="modal fade" id="destroyPick-<%= pick.id%>" role="dialog">
                <div class="modal-dialog modal">

                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Supprimer votre pick ? </h4>
                    </div>
                    <div class="modal-body">
                      <% if pick.state == "pending" %>
                        <h5>Cliquez sur <b>"Supprimer"</b> pour retirer "<%= pick.seed.title %>"" de vos picks, sinon, cliquez sur <b>"Retour"</b>.</h5>
                      <% else %>
                        <h5>En supprimant votre pick vous annulez votre participation à la campagne d'achat pour obtenir <%= pick.seed.title %>. Nous vous remboursons dès maintenant l'intégralité de l'acompte que vous aviez versé. </h5>
                      <% end %>
                    </div>
                    <div class="modal-footer">
                      <div class="action-links">
                        <button type="button" id="close-modal-destroy-<%= pick.id%>" class="btn-dissmiss text-center" data-dismiss="modal">Retour</button>
                        <%= link_to pick_path(pick.id), class: "mid-width  #{'paid' if pick.state == 'paid'}", method: :delete, remote: true do %>
                            <div class="btn seedlap">Supprimer</div>
                          <% end %>
                      </div>
                      <div class="loader-container hidden"></div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <% else %>
        <div class="pick-feed">
          <div class="pick-presentation">
            <h2>Vos picks</h2>
            <p class="no-picks-yet">Vous n'avez encore rien pické jusqu'à présent</p>

            <div class="index-path">
              <%= link_to seeds_path do %>
                <div class="btn btn-default">Y remédier</div>
              <% end %>
            </div>

          </div>
        </div>

    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="page-section">
    <div class="row dashboard">


      <div class="col-xs-12 tabs-info">
        <ul class="nav nav-tabs">
            <li class="active"><a data-target="#public-profile">PROFIL PUBLIC</a></li>
            <li><a data-target="#personal-infos">INFOS PRIVEES</a></li>
        </ul>
        <div class="small-padding">
          <div class="tab-content">
            <div id="public-profile" class="tab-pane fade in active">

              <div class="user-form">
                <%= simple_form_for @user do |f| %>
                  <div class="primary-infos">
                    <div class="photo-update">
                        <%= f.input :photo, as: :attachinary, label: false, class: "upload" %>
                        <% if !@user.photo? %>
                          <div class="no-photo"></div>
                        <% end %>
                        <div class="choosePhoto"><%if @user.photo?%>
                            Changer de photo
                          <% else %>
                            Ajouter photo
                          <% end %>
                        </div>
                    </div>
                    <div class="pseudo-mini-bio">
                      <%= f.input :pseudo, label: false, placeholder: "Pseudo" %>
                      <%= f.input :mini_bio, label: false, placeholder: "Mini-bio" %>
                    </div>
                  </div>
                  <div class="social-options">
                    <h4>Me suivre</h4>
                    <div class="icons-and-form">
                      <div class="social-group">
                        <div class="no-label">
                          <%= image_tag "instagram.png" %>
                          <div class="attached-inputs">
                            <%= f.input :insta, label: false, placeholder: "Vous trouver sur Instagram" %>
                          </div>
                        </div>
                        <div class="no-label">
                          <%= image_tag "youtube.png" %>
                          <div class="attached-inputs">
                            <%= f.input :youtube, label: false, placeholder: "Vous trouver sur Youtube" %>
                          </div>
                        </div>
                      </div>
                      <div class="social-group">
                        <div class="no-label">
                          <%= image_tag "twitter.png" %>
                          <div class="attached-inputs">
                            <%= f.input :twitter, label: false, placeholder: "Vous trouver sur Twitter" %>
                          </div>
                        </div>
                        <div class="no-label">
                          <%= image_tag "facebook.png" %>
                          <div class="attached-inputs">
                            <%= f.input :facebook, label: false, placeholder: "Vous trouver sur Facebook" %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="save-user">
                    <%= link_to user_path(@user) do %>
                      <div class="btn-white hidden">Annuler</div>
                    <% end %>
                    <%= f.button :submit, value: "Enregistrer", id: "update-user" %>
                  </div>
                <% end %>
              </div>
            </div>

            <div id="personal-infos" class="tab-pane fade">
              <div class="user-form">
                <div class="form-box civil">
                  <div class="synthesis">
                    <h3>Profil</h3>
                    <div id="profil-and-pen">
                      <div class="current-infos civil-infos">
                        <%= render 'users/civil', user: @user %>
                      </div>
                      <div class="edit-icon">
                        <span id= "edit-civil" class="glyphicon glyphicon-pencil"></span>
                      </div>
                    </div>
                  </div>
                  <div class="form-civil">
                    <%= simple_form_for @user, :url => update_civil_user_path(@user.id), html: { id: 'update-private'}, remote: true do |f| %>
                      <div class="no-label">
                        <div class="written-label">Sexe</div>
                        <div class="attached-inputs">
                        <%= f.collection_radio_buttons :sex, [["man", 'Homme'] ,["woman", 'Femme']], :first, :last %>
                        </div>
                      </div>
                      <%= f.input :date_of_birth, label:"Date de naissance", as: :date,  start_year: Date.today.year - 18,
                                                    end_year: 1900,
                                                    order: [:day, :month, :year], :prompt => { :month => 'Mois', :year => 'Année', :day => 'Jour' }, use_month_numbers: true  %>
                      <%= f.input :email, label: "Email" %>
                      <div class="action-buttons">
                        <div id= "cancel-civil" class="btn-white">Annuler</div>
                        <%= f.button :submit, value: "Actualiser", id: "submit-update-private" %>
                      </div>
                    <% end %>
                  </div>
                </div>
                <% if  @addresses%>
                <div class="form-box livraison">
                  <div class="synthesis">
                    <h3>Livraison</h3>
                    <div id="address-and-pen">
                      <div class="current-infos address-infos">
                        <%= render 'users/livraison', addresses: @addresses %>
                      </div>
                      <div class="edit-icon">
                        <span id= "edit-address" class="glyphicon glyphicon-pencil"></span>
                      </div>
                    </div>
                  </div>
                  <div class="form-livraison">
                    <%= simple_form_for @addresses, :url => update_address_user_path(@user.id), :method => :patch, remote: true do |f| %>
                      <%= f.input :first_name, label: "Prénom", class: "input-group-field" %>
                      <%= f.input :last_name, label: "Nom", class: "input-group-field" %>
                      <%= f.input :street, label: "Rue et numéro", class: "input-group-field" %>

                      <%= f.input :zip_code, label: "Code postal", class: "input-group-field" %>
                      <%= f.input :city, label: "Ville", class: "input-group-field" %>

                      <%= f.input :address_complement, class: "input-group-field", label: "Complément d'adresse", placeholder: "Autres instructions de livraison: Digicode, Batiment, Société " %>
                      <%= f.input :phone_number, class: "input-group-field", label: "Téléphone", placeholder: "Vous joindre par téléphone" %>
                      <div class="action-buttons">
                        <div id= "cancel-address" class="btn-white">Annuler</div>
                        <%= f.button :submit, value: "Actualiser", id: "submit-update-address" %>
                      </div>
                    <% end %>
                  </div>
                </div>
                <% end %>
                <div class="form-box password">
                  <div class="synthesis">
                    <h3>Sécurité</h3>
                    <div id="password-and-pen">
                      <div class="current-infos">
                        <div class="title-and-data">
                          <div class="title">Mot de passe:</div>
                          <div class="data"><%= image_tag "key.png", class: "key-icon" %></div>
                        </div>
                      </div>
                      <div class="edit-icon">
                        <span id= "edit-password" class="glyphicon glyphicon-pencil"></span>
                      </div>
                    </div>
                  </div>
                  <div class="form-password">
                    <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
                      <%= f.error_notification %>
                        <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
                          <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
                        <% end %>
                        <%= f.input :current_password, label: "Mot de passe actuel", required: true %>
                        <%= f.input :password, autocomplete: "off", placeholder: "minimum 6 carractères", label: "Nouveau mot de passe", required: false %>
                        <%= f.input :password_confirmation, label: "Confirmer", placeholder: "confirmer le nouveau mot de passe", required: false %>
                        <div class="action-buttons">
                          <div id= "cancel-password" class="btn-white">Annuler</div>
                          <%= f.button :submit, value: "Actualiser", id: "submit-update-password" %>
                        </div>
                    <% end %>
                  </div>
                </div>

                <% if @customer_infos %>
                  <div class="form-box paiement">
                    <div class="synthesis">
                      <h3>Paiement</h3>
                      <div id="paiement-and-pen">
                        <div class="current-infos card-infos">
                          <%= render "users/card-infos", customer_infos: @customer_infos %>
                        </div>
                        <div class="edit-icon">
                          <span id= "edit-paiement" class="glyphicon glyphicon-pencil"></span>
                        </div>
                      </div>
                    </div>
                    <div class="form-card">
                      <script src="https://js.stripe.com/v3/"></script>
                      <%= form_tag update_paiement_user_path(@user), id: "update-user-form", method: :patch do %>
                        <div class="form-row">
                          <div class="new-card">
                            Nouvelle carte
                          </div>
                          <div id="card-element">
                            <!-- A Stripe Element will be inserted here. -->
                          </div>

                          <!-- Used to display form errors. -->
                          <div id="card-errors" role="alert"></div>
                        </div>
                        <div class="action-buttons">
                          <div id= "cancel-card" class="btn-white">Annuler</div>
                          <button class= "btn-orange", id="submit-update-card">Actualiser
                          </button>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "shared/update-payment-from-user" %>
<%= render 'shared/footer' %>

app/views/users/update-paiment.js.erb
$(document).ready(function(){
  $(".current-infos.card-infos").html('<%= j render 'users/card-infos', customer_infos: @customer_infos %>');
  $(".form-card").slideToggle();
  $("#paiement-and-pen").slideToggle();
})

app/views/users/update_address.js.erb
$(document).ready(function(){
  $(".current-infos.address-infos").html('<%= j render 'users/livraison', addresses: @addresses %>');
  $(".form-livraison").slideToggle();
  $("#address-and-pen").slideToggle();
})

app/views/users/update_civil.js.erb
$(document).ready(function(){
  $(".current-infos.civil-infos").html('<%= j render 'users/civil', user: @user %>');
  $(".form-civil").slideToggle();
  $("#profil-and-pen").slideToggle();
})