config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"



 root :to => 'pages#home'
 require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users, :controllers => { :registrations => :registrations }
  resources :seeds, only: [:index, :new, :create, :update, :show], shallow: true do
    member do
      patch :update_delivery_costs
      put :update_delivery_costs
    end
    resources :picks, only: [:index, :edit, :show, :create, :update, :destroy] do
      member do
        patch :update_card
        put :update_card
      end
      resources :exchanges, only: [:create, :update]
      resources :payments, only: [:new, :create, :destroy]
    end
    resources :signal_seeds, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [ :show, :edit, :update] do
    member do
        patch :update_address
        put :update_address
        patch :update_paiement
        put :update_paiement
        patch :update_civil
        put :update_civil
      end
  end
  resources :addresses, only: [:create, :update]
  resources :campaigns, only: [:update]


  get 'signaled', to: 'campaigns#signaled'
  get 'pending', to: 'campaigns#pending'
  get 'success', to: 'campaigns#success'
  get 'fail', to: 'campaigns#fail'

  get 'message', to: 'campaigns#message'


  get 'admin', to: 'seeds#admin'
  get 'publish_seed', to: 'seeds#publish_seed'
  get 'newest', to: 'seeds#newest'
  get 'popular', to: 'seeds#popular'
  get 'last_day', to: 'seeds#last_day'

  get 'my_picks', to: 'picks#my_picks'
  get 'pick_history', to: 'picks#pick_history'

  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'contact', to: 'pages#contact'
  get 'mentions_legales', to: 'pages#mentions_legales'
  get 'cgu', to: 'pages#cgu'


end

app/views/shared/_categories.html.erb
<% @categories.each do |category| %>
  <%= link_to seeds_path(category: category) do %>
      <div class="sub-title <%=category.id%> <%='inactive' if category == @filter %>">
        <%= image_tag "#{category.name.downcase.gsub(' ', '_').gsub('é', 'e')}.png", class: "categories-icon" %>
        <div class="name-and-count">
          <p><%= category.name%></p>
        </div>
      </div>
  <% end %>
<% end %>

app/views/shared/_facebook_pixel.html.erb
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '443275032853012');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=443275032853012&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115055409-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-115055409-1');
    </script>

app/views/shared/_hotjar.html.erb
<!-- Hotjar Tracking Code for www.pickalgo.com -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1002573,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

app/views/shared/_how-to-pick.html.erb
<div class="how-to-pick">
<!-- Modal -->
  <div class="modal fade" id="howToPick" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Guide du Pick </h4>
        </div>
        <div class="modal-body-guide">
          <div class="pick-modal">
            <h3 class="pick-guide-title">Faites votre meilleure offre</h3>

            <p class="pick-guide-p">Dites-nous quel prix vous ne souhaitez pas dépasser pour acheter le produit qui vous plaît. Ou autrement dit, <b>le prix maximal </b>que vous êtes prêt à dépenser pour ce produit.</p>

            <h3 class="pick-guide-title">C'est simple</h3>
            <p class="pick-guide-p">Réfléchissez simplement au montant maximal que vous êtes prêt à dépenser pour ce produit. Si nous obtenons un meilleur prix que celui que vous aviez choisi, <b>vous avez la garantie d'en bénéficier.</b></p>

            <h3 class="pick-guide-title">N'ayez aucune stratégie</h3>
            <p class="pick-guide-p">Imaginez que vous soyez prêt à payer 150 € pour un produit. Vous vous dites que vous aimeriez payer encore moins cher, et vous proposez 130 €. <b>Un pick à 130 € plutôt qu'à 150 € n'augmente pas vos chances de l'obtenir à 130 € ou moins cher</b>, mais vous empêchera en revanche de bénéficier d'un prix compris entre 131 et 150 € ! Si à la fin de la campagne, Pickalgo a obtenu un prix de 140 € pour le produit, vous n'avez rien à payer, mais vous ne pouvez malheureusement pas bénéficier du deal.</p>

            <h3 class="pick-guide-title">Et à la fin...</h3>

            <p class="pick-guide-p">A la fin de la campagne d'achat, en fonction du montant de votre pick deux dénouements possibles :</p>

            <p class="pick-guide-p">-Vous aviez pické à un prix supérieur ou égal au prix finalement obtenu par Pickalgo : Vous obtenez le produit au prix final de la campagne.
            Exemple : Vous avez pické à 150 €, le prix obtenu par Pickalgo est de 140€, <b>vous obtenez le produit pour 140 €</b>.</p>

            <p class="pick-guide-p">-Vous aviez pické le produit à un prix inférieur au prix obtenu par Pickalgo : Vous n'avez rien payer, mais ne pouvez pas non plus bénéficier du prix obtenu.
            Exemple : Vous aviez pické à 130 €, le prix obtenu par Pickalgo est de 140 €, <b>vous ne pouvez pas bénéficier du deal</b>.</p>

          </div>
        </div>
        <div class="modal-footer hidden">
          <button type="button" id="close-how-to-pick" class="btn btn-default text-center" data-dismiss="modal"></button>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_last_day_categories.html.erb
<% @categories.each do |category| %>
  <%= link_to last_day_path(category: category) do %>
      <div class="sub-title <%=category.id%> <%='inactive' if category == @filter %>">
        <%= image_tag "#{category.name.downcase.gsub(' ', '_').gsub('é', 'e')}.png", class: "categories-icon" %>
        <div class="name-and-count">
          <p><%= category.name%></p>
        </div>
      </div>
  <% end %>
<% end %>

app/views/shared/_minimal-navbar.html.erb
<div class="navbar-container">
  <div class="navbar">

    <!-- Logo -->
    <%= link_to seeds_path do %>
      <%= image_tag "logo.png", id: "logo" %>
    <% end %>


  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div id="top-link"></div>
  <div class="navbar">

    <!-- Logo -->
    <%= link_to seeds_path do %>
      <%= image_tag "logo.png", id: "logo" %>
    <% end %>

    <!-- Right Navigation -->
    <% if user_signed_in? %>
      <div class="hidden-xs">
        <div class="navbar-right">
          <div class="my-picks">
            <%= render "shared/pending-picks" %>
            <span class="tooltiptext">Mes picks</span>
          </div>

          <div class="user-menu">
            <div class="dropdown">
              <% if current_user.photo? %>
                <%= cl_image_tag current_user.photo.path, :width=>110, :height=>110, class: "dropdown-toggle", id: "dropdown-photo", "data-toggle" => "dropdown" %>
              <% else %>
                <i class="fa fa-user dropdown-toggle" aria-hidden="true" id="dropdown-icon", data-toggle="dropdown"></i>
              <% end %>
              <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
                <li>
                  <%= link_to user_path(current_user) do %>
                    <i class="fa fa-user-circle"></i> <%= t(".profile", default: "Profil") %>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Déconnecter") %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>

          <% if policy(Seed).admin? %>
            <%= link_to admin_path do %>
              <i class="fa fa-user-plus" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="hidden-sm hidden-md hidden-lg">
        <div class="navbar-right">
          <div class="my-picks">
            <%= render "shared/pending-picks" %>
            <span class="tooltiptext">Mes picks</span>
          </div>
          <div class="user-menu">
            <div class="dropdown">
              <% if current_user.photo? %>
                <%= cl_image_tag current_user.photo.path, class: "dropdown-toggle", id: "dropdown-photo", "data-toggle" => "dropdown" %>
              <% else %>
                <i class="fa fa-user dropdown-toggle" aria-hidden="true" id="dropdown-icon", data-toggle="dropdown"></i>
              <% end %>
              <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
                <li>
                  <%= link_to user_path(current_user) do %>
                    <i class="fa fa-user-circle"></i> <%= t(".profile", default: "Profil") %>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_seed_path do %>
                    <i class="fa fa-plus" aria-hidden="true"></i> <%= t(".new_seed_xs", default: "Poster") %>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Déconnecter") %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
          <% if policy(Seed).admin? %>
            <%= link_to admin_path do %>
              <i class="fa fa-user-plus" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </div>
      </div>

      <% else %>
        <div class="navbar-right">
          <%= link_to new_user_registration_path do%>
            <div class="btn-blue">Mon compte</div>
          <% end %>
        </div>

    <% end %>
  </div>
</div>

app/views/shared/_pending-picks.html.erb
<%= link_to my_picks_path do %>
  <div class="complete-link">
      <%= image_tag "blue-icon.png", class: "pending pick-icon" %>
      <%pending_picks = Pick.pending_picks(current_user).includes(:seed).select {|pick| pick.seed.ongoing?} %>
      <% if pending_picks.any?  %>
        <div class="picks-pending">
          <%= pending_picks.count %>
        </div>
      <% end %>
    </i>
  </div>
<% end %>

app/views/shared/_right-encart.html.erb
<div class="right-container">
  <div class="encart-element background">
    <h3>Présenter un produit</h3>
    <div class="pic-text">
      <%= image_tag "star.png", class: "star-icon" %>
      <p>Vous venez de découvrir un super produit</p>
    </div>
    <div class="pic-text">
      <%= image_tag "star.png", class: "star-icon" %>
      <p>Vous pensez qu'il pourrait adopter un autre prix</p>
    </div>
    <div class="pic-text">
      <%= image_tag "star.png", class: "star-icon" %>
      <p>Vous souhaitez partager votre découverte</p>
    </div>
    <%= link_to new_seed_path, class:"cta-container" do %>
      <div class="cta-button btn-orange"><span>+ </span>  Présentez le</div>
    <% end %>
  </div>
  <% unless @picks.blank? %>
    <div class="encart-element background">
      <h3 class="last-picks-title">Picks les plus récents</h3>
      <% unless @pick_1.blank? %>
        <%= link_to seed_path(@pick_1.seed), class:"pic-text last-picks" do %>
            <%= cl_image_tag("#{@pick_1.seed.photos.first.path}", :width=>45, :height=>45, :crop=>"fill", class: "pick-image")%>
            <div><h5><%= @pick_1.seed.title %></h5>
              <div class="category">
                <p><%= @pick_1.seed.category.name %></p>
              </div>
            </div>
        <% end %>
      <% end %>
      <% unless @pick_2.blank? %>
        <%= link_to seed_path(@pick_2.seed), class:"pic-text last-picks" do %>
            <%= cl_image_tag("#{@pick_2.seed.photos.first.path}", :width=>45, :height=>45, :crop=>"fill", class: "pick-image")%>
            <div><h5><%= @pick_2.seed.title %></h5>
              <div class="category">
                <p><%= @pick_2.seed.category.name %></p>
              </div>
            </div>
        <% end %>
      <% end %>
      <% unless @pick_3.blank? %>
        <%= link_to seed_path(@pick_3.seed), class:"pic-text last-picks" do %>
          <%= cl_image_tag("#{@pick_3.seed.photos.first.path}", :width=>45, :height=>45, :crop=>"fill", class: "pick-image")%>
          <div><h5><%= @pick_3.seed.title %></h5>
            <div class="category">
              <p><%= @pick_3.seed.category.name %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class="encart-element background">
    <h3>Une remarque ?</h3>
    <p>Pickalgo est actuellement en version beta, si vous décelez un bug, avez une suggestion, ou un mot d'amour à nous faire passer, c'est par ici ↓</p>
    <%= link_to contact_path, class:"cta-container" do %>
      <div class="cta-button btn-white">Nous contacter</div>
    <% end %>
  </div>
  <div class="encart-element">
    <div class="links-container">
      <%= link_to "FAQ", faq_path %>
      <%= link_to "Contact", contact_path %>
      <%= link_to "CGU", cgu_path %>
      <%= link_to "Mentions légales", mentions_legales_path %>
    </div>
    <h4>
      <%= image_tag "gray-logo.png", class: "gray-logo" %>
      <span>©Beta 2018</span>
    </h4>
  </div>

</div>

app/views/shared/_stripe-form.html.erb
<% content_for(:after_js) do %>
  <script>
    var stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
      base: {
        color: '#32325d',
        lineHeight: '18px',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
          color: '#aab7c4'
        }
      },
      invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
      }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');
    card.addEventListener('change', function(event) {
      var displayError = document.getElementById('card-errors');
      if (event.error) {
        displayError.textContent = event.error.message;
      } else {
        displayError.textContent = '';
      }
    });
    // Create a token or display an error when the form is submitted.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
      event.preventDefault();

      var firstName = $("#address_first_name").val();
      var lastName = $("#address_last_name").val();
      var addressStreet = $("#address_street").val();
      var zipCode = $("#address_zip_code").val();
      var city = $("#address_city").val();

      if (firstName != "" && lastName != "" && addressStreet != "" && zipCode != "" && city != "" ) {
        $("#validate-paiement").hide();
        $(".loader-container").removeClass("hidden").html("<div class='loader'></div>");
        $(".update-delivery-infos").click();

        stripe.createToken(card).then(function(result) {
          if (result.error) {
            // Inform the customer that there was an error.
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
          } else {

            // Send the token to your server.
            stripeTokenHandler(result.token);

          }
        });


      } else {

        if (firstName == "" || lastName == "" || addressStreet == "" || zipCode == "" || city == "" ) {
          if ($(".fa.fa-user").hasClass("shake")) {
            $(".fa.fa-user").removeClass("shake");
          }
          if ($(".fa.fa-truck").hasClass("shake")) {
            $(".fa.fa-truck").removeClass("shake");
          }
          $("#go-to-form").click();
        }

        if (firstName == "" || lastName == "" ) {
          setTimeout(function(){
            $(".fa.fa-user").addClass("shake").css({ 'color': 'red', 'border-color': 'red' });
        }, 1000);
         } else {
           $(".fa.fa-user").removeAttr('style');
         } if (addressStreet == "" || zipCode == "" || city == "" ) {
             setTimeout(function(){
               $(".fa.fa-truck").addClass("shake").css({ 'color': 'red', 'border-color': 'red' });
           }, 1000);
         } else {
           $(".fa.fa-truck").removeAttr('style');
         }
      }

    });
    function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    setTimeout(function(){
      form.submit();
    }, 500);


    }
    </script>
  <% end %>

app/views/shared/_sub-navbar.html.erb
<div class="sub-container hidden-xs">
  <div class="sub-nav">
    <%= link_to seeds_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-globe"></div>
        <p>Tout</p>
      </div>
    <% end %>
    <%= link_to popular_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-fire"></div>
        <p>Tendances</p>
      </div>
    <% end %>
    <%= link_to newest_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-leaf"></div>
        <p>Récents</p>
      </div>
    <% end %>
    <%= link_to last_day_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-flash"></div>
        <p>Dernier jour</p>
      </div>
    <% end %>
    <%= link_to seed_path(@sample) do %>
    <div class="cat">
      <div class="filter-icon glyphicon glyphicon-random"></div>
      <p>Hasard</p>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_update-payment-from-user.html.erb
<% content_for(:after_js) do %>
  <script>
    var stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
      base: {
        color: '#32325d',
        lineHeight: '18px',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
          color: '#aab7c4'
        }
      },
      invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
      }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');
    card.addEventListener('change', function(event) {
      var displayError = document.getElementById('card-errors');
      if (event.error) {
        displayError.textContent = event.error.message;
      } else {
        displayError.textContent = '';
      }
    });
    // Create a token or display an error when the form is submitted.
    var form = document.getElementById('update-user-form');
    form.addEventListener('submit', function(event) {
      event.preventDefault();




      stripe.createToken(card).then(function(result) {
        if (result.error) {
          // Inform the customer that there was an error.
          var errorElement = document.getElementById('card-errors');
          errorElement.textContent = result.error.message;
        } else {

            stripeTokenHandler(result.token);
        }
      });
    });
    function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('update-user-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();

    }
    </script>
  <% end %>