config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"



 root :to => 'pages#home'
 require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users, :controllers => { :registrations => :registrations }
  resources :seeds, only: [:index, :new, :create, :update, :show], shallow: true do
    member do
      patch :update_delivery_costs
      put :update_delivery_costs
    end
    resources :picks, only: [:index, :edit, :show, :create, :update, :destroy] do
      member do
        patch :update_card
        put :update_card
      end
      resources :exchanges, only: [:create, :update]
      resources :payments, only: [:new, :create, :destroy]
    end
    resources :signal_seeds, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [ :show, :edit, :update] do
    member do
        patch :update_address
        put :update_address
        patch :update_paiement
        put :update_paiement
        patch :update_civil
        put :update_civil
      end
  end
  resources :addresses, only: [:create, :update]
  resources :campaigns, only: [:update]


  get 'signaled', to: 'campaigns#signaled'
  get 'pending', to: 'campaigns#pending'
  get 'success', to: 'campaigns#success'
  get 'fail', to: 'campaigns#fail'

  get 'message', to: 'campaigns#message'


  get 'admin', to: 'seeds#admin'
  get 'publish_seed', to: 'seeds#publish_seed'
  get 'newest', to: 'seeds#newest'
  get 'popular', to: 'seeds#popular'
  get 'last_day', to: 'seeds#last_day'

  get 'my_picks', to: 'picks#my_picks'
  get 'pick_history', to: 'picks#pick_history'

  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'contact', to: 'pages#contact'
  get 'mentions_legales', to: 'pages#mentions_legales'
  get 'cgu', to: 'pages#cgu'


end

app/models/seed.rb
class Seed < ApplicationRecord
  after_create :pick_reminder
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one :campaign, dependent: :destroy
  belongs_to :category
  belongs_to :user
  has_many :picks, dependent: :destroy
  has_many :signal_seed, dependent: :destroy


  self.per_page = 10




  validates :title,
    presence: {
    message: "Nom du produit requis"
    }
  validates :title, uniqueness: {
    message: "Produit déjà posté"
    }

  validates :title, length: { minimum: 5 }

  validates :description,
    presence: {
    message: "Description personnelle obligatoire"
    }

  validates :description,  length: { minimum: 5,
    too_short: "%{count} carractères au minimum" }

  validates :category_id, presence: {
    message: "Attribuez une catégorie au produit"
    }

  validates :photos, presence: {
    message: "Ajoutez au moins une photo"
    }

  validates :sale_point_url,
    presence: {
    message: "Premettre aux utilisateurs d'obtenir plus d'infos sur le produit"
    }

  validates :sale_point_url, url: true

  validates :url, url: true

  # validates :size_guide, presence: true, if: :mode?




  has_attachments :photos, maximum: 5

  scope :category, -> (category) { where category: category}
  scope :popular, -> { order(popularity: :desc) }
  scope :newest, -> { order(expiration: :desc)}
  scope :ongoing, -> { where('expiration > ?', DateTime.now)}
  scope :expired, -> { where('expiration < ?', DateTime.now)}
  scope :last_day, -> { where('expiration < ?', (DateTime.now + 1.days))}

  def set_expiration
    self.expiration = DateTime.now + 7.days
  end


  def increment_views
    self.view_counter += 1
    save!
  end


  def increment_popularity
    self.popularity = (self.view_counter + self.picks.count * 5)
    save!
  end

  def extract_seed_photos
    collection = []
    self.photos.each do |photo|
      collection << photo
    end
    return collection
  end

  def ongoing?
    self.expiration > DateTime.now
  end

  def self.seed_selection
    ongoing.where(status:"published", admin_review: ["Valide", "not-reviewed"])
  end

  def self.seed_sample_expired
    where(status:"published", admin_review: ["Valide", "not-reviewed"])
  end

  def cancel_campaign
    self.picks.each do |pick|
      pick.state = "cancelled"
      pick.save
    end
  end


  def pick_reminder
    SendPickReminderJob.set(wait: 6.days).perform_later(self.id)
  end



end

app/controllers/seeds_controller.rb
class SeedsController < ApplicationController

  before_action :set_sample, only: [:index, :last_day, :popular, :newest, :show, :new]
  before_action :last_picks, only: [:index, :last_day, :popular, :newest]
  skip_before_action :authenticate_user!, only: [:index, :last_day, :popular, :newest, :show]
  before_action :set_user, only: [:index, :last_day, :popular, :newest, :show, :new]


  def index
    @categories = Category.all
    if params[:category].present?
      @filter = Category.friendly.find(params[:category])
      @seeds = policy_scope(Seed).seed_selection.includes(:category, :user).paginate(page: params[:page])
      @seeds = @seeds.category(@filter)
    else
      @seeds = policy_scope(Seed).seed_selection.includes(:category, :user).paginate(page: params[:page])
    end
    respond_to do |format|
      format.html
      format.js { render 'shared/seed_page' }
    end
  end

  def last_day
    @categories = Category.all
    if params[:category].present?
      @filter = Category.friendly.find(params[:category])
      @seeds = Seed.seed_selection.last_day.includes(:category, :user).paginate(page: params[:page])
      @seeds = @seeds.category(@filter)
    else
      @seeds = Seed.seed_selection.last_day.includes(:category, :user).paginate(page: params[:page])
    end
    authorize @seeds
    respond_to do |format|
      format.html
      format.js { render 'shared/seed_page' }
    end
  end

  def popular
    @categories = Category.all
    if params[:category].present?
      @filter = Category.friendly.find(params[:category])
      @seeds = Seed.seed_selection.popular.includes(:category, :user).paginate(page: params[:page])
      @seeds = @seeds.category(@filter)
    else
      @seeds = Seed.seed_selection.popular.includes(:category, :user).paginate(page: params[:page])
    end
    authorize @seeds
    respond_to do |format|
      format.html
      format.js { render 'shared/seed_page' }
    end
  end

  def newest
    @categories = Category.all
    if params[:category].present?
      @filter = Category.friendly.find(params[:category])
      @seeds = Seed.seed_selection.newest.includes(:category, :user).paginate(page: params[:page])
      @seeds = @seeds.category(@filter)
    else
      @seeds = Seed.seed_selection.newest.includes(:category, :user).paginate(page: params[:page])
    end
    authorize @seeds
    respond_to do |format|
      format.html
      format.js { render 'shared/seed_page' }
    end
  end



  def new
    @seed = Seed.new
    @mode_category_id = Category.where(name: 'Mode').first.id
    authorize @seed
  end


  def create
     @seed = current_user.seeds.build(seed_params)
     authorize @seed
    if @seed.save
      redirect_to seed_path(@seed)
    else
      render :new
    end
  end

  def show
    @seed = Seed.friendly.find(params[:id])
    authorize @seed
    @seeder = @seed.user
    @seed.increment_views
    @seed.increment_popularity
    @pick = Pick.new
    @user = current_user
    unless @user.blank?
      @my_pick = Pick.my_pick(@user, @seed).first
    end
  end

  def update
    @seed = Seed.friendly.find(params["id"])
    admin_review = params["seed"]["admin_review"]
    authorize @seed

    if admin_review == "Valide"
      @seed.update(admin_review_params)
      redirect_to signaled_path

    else
      @seed.cancel_campaign
      @seed.update(admin_review_params)
      redirect_to signaled_path
    end

  end

  def update_delivery_costs
    @seed = Seed.find(params[:id])
    authorize @seed
    status = params["seed"]["status"]
    @user = @seed.user.id
    if status == "published"
      @seed.set_expiration
      @seed.update(delivery_costs_infos)
      Campaign.create(seed_id: @seed.id)
      PublishSeedMailer.seed_validated(@seed.id, @user).deliver_later
      redirect_to publish_seed_path
    else
      @seed.update(delivery_costs_infos)
      PublishSeedMailer.seed_rejected(@seed.id, @user).deliver_later
      redirect_to publish_seed_path
    end
  end



  def admin
    @pending = @pending = Seed.where.not(admin_review:"Invalide").includes(:campaign).joins(:campaign).where(campaigns: {status: "pending"})
    @signaled = Seed.where(admin_review: "not-reviewed").joins(:signal_seed).distinct
    @picks =  Pick.joins(:exchanges).where(exchanges: { admin_review: false }).distinct
    @seeds = Seed.where(status: "pending").count
    @seed = Seed.first
    authorize @seed
  end

  def publish_seed
    @seeds = Seed.where(status: "pending")
    authorize @seeds
  end


  private

  def seed_params
    params.require(:seed).permit(:title, :size_guide, :description, :sale_point_url, :sale_point_contact, :category_id, :url, :secondary_url, photos: [])
  end

  def admin_review_params
    params.require(:seed).permit(:admin_review)
  end

  def set_user
    @user = current_user
  end

  def delivery_costs_infos
    params.require(:seed).permit(:expedition_costs, :status)
  end

  def last_picks
    @picks = Pick.includes(:seed).all.group_by(&:seed_id).map{|s| s.last.last}.last(3)
    @pick_1 = @picks[0]
    @pick_2 = @picks[1]
    @pick_3 = @picks[2]
  end


end

app/views/seeds/_index-modals.html.erb
<!-- Modal -->
<div id="filter-xs" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Filtrer</h4>
      </div>
      <div class="modal-body">
        <div class="filter-title">
          <div class="filter-header">
           <% if @filter %>
            <p class="filter-before">DÉFILTRER</p>
            <%= link_to seeds_path do %>
             <i class="fa fa-toggle-on xs-fa" aria-hidden="true"></i>
            <% end %>
           <% end %>
          </div>
          <div class="sub-categories">
            <%= render "shared/categories", categories: @categories %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div id="filter-xs-cat" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Trier</h4>
      </div>
      <div class="modal-body">
        <div class="filter-title">
          <div class="sub-categories">
            <%= link_to seeds_path do %>
              <div class="sub-title inactive">
                <div class="filter-icon glyphicon glyphicon-globe"></div>
                <p>Tout</p>
              </div>
            <% end %>
            <%= link_to popular_path do %>
              <div class="sub-title">
                <div class="filter-icon glyphicon glyphicon-fire"></div>
                <p>Tendances</p>
              </div>
            <% end %>
            <%= link_to newest_path do %>
              <div class="sub-title">
                <div class="filter-icon glyphicon glyphicon-leaf"></div>
                <p>Récents</p>
              </div>
            <% end %>
            <%= link_to last_day_path do %>
              <div class="sub-title">
                <div class="filter-icon glyphicon glyphicon-flash"></div>
                <p>Dernier jour</p>
              </div>
            <% end %>
            <%= link_to seed_path(@sample) do %>
            <div class="sub-title">
              <div class="filter-icon glyphicon glyphicon-random"></div>
              <p>Hasard</p>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/seeds/_last-day-modals.html.erb
<!-- Modal -->
<div id="filter-xs" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Filtrer</h4>
      </div>
      <div class="modal-body">
        <div class="filter-title">
          <div class="filter-header">
           <% if @filter %>
            <p class="filter-before">DÉFILTRER</p>
            <%= link_to seeds_path do %>
             <i class="fa fa-toggle-on xs-fa" aria-hidden="true"></i>
            <% end %>
           <% end %>
          </div>
          <div class="sub-categories">
            <%= render "shared/categories", categories: @categories %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div id="filter-xs-cat" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Trier</h4>
      </div>
      <div class="modal-body">
        <div class="filter-title">
          <div class="sub-categories">
            <%= link_to seeds_path do %>
              <div class="sub-title">
                <div class="filter-icon glyphicon glyphicon-globe"></div>
                <p>Tout</p>
              </div>
            <% end %>
            <%= link_to popular_path do %>
              <div class="sub-title">
                <div class="filter-icon glyphicon glyphicon-fire"></div>
                <p>Tendances</p>
              </div>
            <% end %>
            <%= link_to newest_path do %>
              <div class="sub-title">
                <div class="filter-icon glyphicon glyphicon-leaf"></div>
                <p>Récents</p>
              </div>
            <% end %>
            <%= link_to last_day_path do %>
              <div class="sub-title inactive">
                <div class="filter-icon glyphicon glyphicon-flash"></div>
                <p>Dernier jour</p>
              </div>
            <% end %>
            <%= link_to seed_path(@sample) do %>
            <div class="sub-title">
              <div class="filter-icon glyphicon glyphicon-random"></div>
              <p>Hasard</p>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/seeds/_newest-modals.html.erb
<!-- Modal -->
<div id="filter-xs" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Filtrer</h4>
      </div>
      <div class="modal-body">
        <div class="filter-title">
          <div class="filter-header">
           <% if @filter %>
            <p class="filter-before">DÉFILTRER</p>
            <%= link_to seeds_path do %>
             <i class="fa fa-toggle-on xs-fa" aria-hidden="true"></i>
            <% end %>
           <% end %>
          </div>
          <div class="sub-categories">
            <%= render "shared/categories", categories: @categories %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div id="filter-xs-cat" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Trier</h4>
      </div>
      <div class="modal-body">
        <div class="filter-title">
          <div class="sub-categories">
            <%= link_to seeds_path do %>
              <div class="sub-title">
                <div class="filter-icon glyphicon glyphicon-globe"></div>
                <p>Tout</p>
              </div>
            <% end %>
            <%= link_to popular_path do %>
              <div class="sub-title">
                <div class="filter-icon glyphicon glyphicon-fire"></div>
                <p>Tendances</p>
              </div>
            <% end %>
            <%= link_to newest_path do %>
              <div class="sub-title inactive">
                <div class="filter-icon glyphicon glyphicon-leaf"></div>
                <p>Récents</p>
              </div>
            <% end %>
            <%= link_to last_day_path do %>
              <div class="sub-title">
                <div class="filter-icon glyphicon glyphicon-flash"></div>
                <p>Dernier jour</p>
              </div>
            <% end %>
            <%= link_to seed_path(@sample) do %>
            <div class="sub-title">
              <div class="filter-icon glyphicon glyphicon-random"></div>
              <p>Hasard</p>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/seeds/_publish_seeds.html.erb
<% seeds.each do |seed| %>
<div class="product id-<%= seed.category_id%>">
    <div class='product-body'>
      <div class="head-seed">
        <%= link_to seed_path(seed) do  %>
          <h3> <%= seed.title %>: id <%= seed.id %></h3>
        <% end %>
      </div>

      <div class="bottom-sexion">
        <%= simple_form_for seed, :url => update_delivery_costs_seed_path(seed.id), :method => :patch do |f| %>
        <%= f.collection_radio_buttons :status, [["reject", 'Rejetter'] ,["published", 'Publier']], :first, :last %>
          <%= f.input_field :expedition_costs, placeholder: 'Exemple: 4.90'%>
          <%= f.button :submit, value: "Enregistrer", class: "validate-btn"%>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/seeds/admin.html.erb
<div class="page-container">
  <div class="page-sections">
    <div class="all-cards">
      <%= link_to publish_seed_path, class: "admin-card" do %>
          <i class="filter-icon fas fa-hourglass-start"></i>
          <p>Publish (<%= @seeds %>)</p>
      <% end %>
      <%= link_to message_path, class: "admin-card" do %>
          <div class="filter-icon fa fa-envelope"></div>
          <p>Messages (<%= @picks.size %>)</p>
      <% end %>
      <%= link_to pending_path, class: "admin-card" do %>
          <div class="filter-icon fa fa-pause"></div>
          <p>Pending (<%= @pending.count %>)</p>
      <% end %>
      <%= link_to success_path, class: "admin-card" do %>
          <div class="filter-icon far fa-thumbs-up"></div>
          <p>Success</p>
      <% end %>
      <%= link_to fail_path, class: "admin-card" do %>
          <div class="filter-icon far fa-thumbs-down"></div>
          <p>Fail</p>
      <% end %>
      <%= link_to signaled_path, class: "admin-card" do %>
          <div class="filter-icon glyphicon glyphicon-exclamation-sign"></div>
          <p>Signaled (<%= @signaled.count %>)</p>
      <% end %>
      <%= link_to sidekiq_web_path, class: "admin-card" do %>
          <div class="filter-icon far fa-arrow-alt-circle-left"></div>
          <p>Sidekiq Jobs</p>
      <% end %>
    </div>
  </div>
</div>

app/views/seeds/index.html.erb
<div class="sub-container">
  <div class="sub-nav">
    <%= link_to seeds_path do %>
      <div class="cat selected">
        <div class="filter-icon glyphicon glyphicon-globe"></div>
        <p>Tout</p>
      </div>
    <% end %>
    <%= link_to popular_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-fire"></div>
        <p>Tendances</p>
      </div>
    <% end %>
    <%= link_to newest_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-leaf"></div>
        <p>Récents</p>
      </div>
    <% end %>
    <%= link_to last_day_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-flash"></div>
        <p>Dernier jour</p>
      </div>
    <% end %>
    <%= link_to seed_path(@sample) do %>
    <div class="cat">
      <div class="filter-icon glyphicon glyphicon-random"></div>
      <p>Hasard</p>
    </div>
    <% end %>
  </div>
</div>

<div class="page-container">
  <%= render "seeds/index-modals" %>

  <div class=" filter-xs">
    <!-- Trigger the modal with a button -->
    <div id="fixed-modal-trigger"><span class="glyphicon glyphicon-filter"></span></div>

    <button type="button" class="btn hidden" id="real-trigger" data-toggle="modal" data-target="#filter-xs"></button>

    <%= link_to new_seed_path, class:"cta-xs-button" do %>
      <div id="new-seed-link"><span class="glyphicon glyphicon-plus"></span></div>
    <% end %>

    <!-- Trigger the modal with a button -->
    <div id="fixed-modal-trigger-cat"><span class="glyphicon glyphicon-th-list"></span></div>

    <button type="button" class="btn hidden" id="real-trigger-cat" data-toggle="modal" data-target="#filter-xs-cat"></button>
  </div>



  <div class="seed-feed">

    <div class="categories">

      <div class="filter-title">
        <div class="filter-header">
        <% if @filter %>
           <p class="filter-before">DEFILTRER</p>
           <%= link_to seeds_path do %>
            <i class="fa fa-toggle-on" aria-hidden="true"></i>
           <% end %>
          <% else %>
            <p class="filter-before">FILTRER</p>
          <% end %>
        </div>
        <div class="sub-categories">
        <%= render "shared/categories", categories: @categories %>
        </div>
      </div>
    </div>

    <% if @seeds.blank? %>
      <div class="no-seed">
        <h1>Pas de campagne en cours.</h1>
        <%= link_to "Lancez la votre !", new_seed_path, class: "cta-new" %>
      </div>
    <% else %>
      <div class="seed-presentation">
        <div id="infinite-scrolling">
          <%= will_paginate @seeds %>
        </div>
        <%= render @seeds%>
      </div>
    <% end %>

    <%= render "shared/right-encart" %>




  </div>
</div>

app/views/seeds/last_day.html.erb
<div class="sub-container hidden-xs">
  <div class="sub-nav">
    <%= link_to seeds_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-globe"></div>
        <p>Tout</p>
      </div>
    <% end %>
    <%= link_to popular_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-fire"></div>
        <p>Tendances</p>
      </div>
    <% end %>
    <%= link_to newest_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-leaf"></div>
        <p>Récents</p>
      </div>
    <% end %>
    <%= link_to last_day_path do %>
      <div class="cat selected">
        <div class="filter-icon glyphicon glyphicon-flash"></div>
        <p>Dernier jour</p>
      </div>
    <% end %>
    <%= link_to seed_path(@sample) do %>
    <div class="cat">
      <div class="filter-icon glyphicon glyphicon-random"></div>
      <p>Hasard</p>
    </div>
    <% end %>
  </div>
</div>

<div class="page-container">
  <%= render "seeds/last-day-modals" %>

  <div class=" filter-xs">
    <!-- Trigger the modal with a button -->
    <div id="fixed-modal-trigger"><span class="glyphicon glyphicon-filter"></span></div>

    <button type="button" class="btn hidden" id="real-trigger" data-toggle="modal" data-target="#filter-xs"></button>

    <%= link_to new_seed_path, class:"cta-xs-button" do %>
      <div id="new-seed-link"><span class="glyphicon glyphicon-plus"></span></div>
    <% end %>

    <!-- Trigger the modal with a button -->
    <div id="fixed-modal-trigger-cat"><span class="glyphicon glyphicon-th-list"></span></div>

    <button type="button" class="btn hidden" id="real-trigger-cat" data-toggle="modal" data-target="#filter-xs-cat"></button>
  </div>

  <div class="seed-feed">


    <div class="categories hidden-xs">

      <div class="filter-title">
        <div class="filter-header">
        <% if @filter %>
           <p class="filter-before">DEFILTRER</p>
           <%= link_to last_day_path do %>
            <i class="fa fa-toggle-on" aria-hidden="true"></i>
           <% end %>
          <% else %>
            <p class="filter-before">FILTRER</p>
          <% end %>
        </div>
        <div class="sub-categories">
          <%= render "shared/last_day_categories", categories: @categories %>
        </div>
      </div>
    </div>
    <% if @seeds.blank? %>
      <div class="no-seed">
        <h1>Pas de campagne en cours de clôture.</h1>
        <p>Peut-être demain !</p>
      </div>
    <% else %>
      <div class="seed-presentation">
        <div id="infinite-scrolling">
          <%= will_paginate @seeds %>
        </div>
        <%= render @seeds%>
      </div>
    <% end %>
    <%= render "shared/right-encart" %>

  </div>
</div>

app/views/seeds/mon_seedoak.html.erb
<h1>Mon Seedoak</h1>
<p>Les seeds qui correspondent à vos préférences</p>

<% @seeds.each do |seed| %>
    <div class="product">

      <div class='product-upvote'>
        <div class="product-arrow"></div>

          <div class='product-count'><%= seed.picks.size %> </div>

      </div>
       <%= link_to seed_path(seed) do  %>
        <%= cl_image_tag seed.photos.first.path, width: 300, height: 200, class: "product-image" %>
        <% end %>

          <div class='product-body'> <%= link_to seed_path(seed) do  %>
            <h3> <%= seed.title %></h3>
            <p>présenté par <%= cl_image_tag(seed.user.photo.path, class: "seeder-picture")%> <%= seed.user.pseudo %></p>
            <p> <%= seed.description%></p>
            <% end %>
          </div>

    </div>
<% end %>

<%= link_to "Créér un nouveau seed", new_seed_path, {class: "btn btn-primary"}  %>

app/views/seeds/newest.html.erb
<div class="sub-container hidden-xs">
  <div class="sub-nav">
    <%= link_to seeds_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-globe"></div>
        <p>Tout</p>
      </div>
    <% end %>
    <%= link_to popular_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-fire"></div>
        <p>Tendances</p>
      </div>
    <% end %>
    <%= link_to newest_path do %>
      <div class="cat selected">
        <div class="filter-icon glyphicon glyphicon-leaf"></div>
        <p>Récents</p>
      </div>
    <% end %>
    <%= link_to last_day_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-flash"></div>
        <p>Dernier jour</p>
      </div>
    <% end %>
    <%= link_to seed_path(@sample) do %>
    <div class="cat">
      <div class="filter-icon glyphicon glyphicon-random"></div>
      <p>Hasard</p>
    </div>
    <% end %>
  </div>
</div>

<div class="page-container">
  <%= render "seeds/newest-modals" %>

  <div class=" filter-xs">
    <!-- Trigger the modal with a button -->
    <div id="fixed-modal-trigger"><span class="glyphicon glyphicon-filter"></span></div>

    <button type="button" class="btn hidden" id="real-trigger" data-toggle="modal" data-target="#filter-xs"></button>

    <%= link_to new_seed_path, class:"cta-xs-button" do %>
      <div id="new-seed-link"><span class="glyphicon glyphicon-plus"></span></div>
    <% end %>

    <!-- Trigger the modal with a button -->
    <div id="fixed-modal-trigger-cat"><span class="glyphicon glyphicon-th-list"></span></div>

    <button type="button" class="btn hidden" id="real-trigger-cat" data-toggle="modal" data-target="#filter-xs-cat"></button>
  </div>
  <div class="seed-feed">


    <div class="categories hidden-xs">

      <div class="filter-title">
        <div class="filter-header">
        <% if @filter %>
           <p class="filter-before">DEFILTRER</p>
           <%= link_to newest_path do %>
            <i class="fa fa-toggle-on" aria-hidden="true"></i>
           <% end %>
          <% else %>
            <p class="filter-before">FILTRER</p>
          <% end %>
        </div>
        <div class="sub-categories">
          <%= render "shared/newest_categories", categories: @categories %>
        </div>
      </div>
    </div>

    <% if @seeds.blank? %>
      <div class="no-seed">
        <h1>Pas de campagne en cours.</h1>
        <%= link_to "Lancez la votre !", new_seed_path, class: "cta-new" %>
      </div>
    <% else %>
      <div class="seed-presentation">
        <div id="infinite-scrolling">
          <%= will_paginate @seeds %>
        </div>
        <%= render @seeds%>
      </div>
    <% end %>
    <%= render "shared/right-encart" %>

  </div>
</div>