config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"



 root :to => 'pages#home'
 require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users, :controllers => { :registrations => :registrations }
  resources :seeds, only: [:index, :new, :create, :update, :show], shallow: true do
    member do
      patch :update_delivery_costs
      put :update_delivery_costs
    end
    resources :picks, only: [:index, :edit, :show, :create, :update, :destroy] do
      member do
        patch :update_card
        put :update_card
      end
      resources :exchanges, only: [:create, :update]
      resources :payments, only: [:new, :create, :destroy]
    end
    resources :signal_seeds, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [ :show, :edit, :update] do
    member do
        patch :update_address
        put :update_address
        patch :update_paiement
        put :update_paiement
        patch :update_civil
        put :update_civil
      end
  end
  resources :addresses, only: [:create, :update]
  resources :campaigns, only: [:update]


  get 'signaled', to: 'campaigns#signaled'
  get 'pending', to: 'campaigns#pending'
  get 'success', to: 'campaigns#success'
  get 'fail', to: 'campaigns#fail'

  get 'message', to: 'campaigns#message'


  get 'admin', to: 'seeds#admin'
  get 'publish_seed', to: 'seeds#publish_seed'
  get 'newest', to: 'seeds#newest'
  get 'popular', to: 'seeds#popular'
  get 'last_day', to: 'seeds#last_day'

  get 'my_picks', to: 'picks#my_picks'
  get 'pick_history', to: 'picks#pick_history'

  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'contact', to: 'pages#contact'
  get 'mentions_legales', to: 'pages#mentions_legales'
  get 'cgu', to: 'pages#cgu'


end

app/models/pick.rb
class Pick < ApplicationRecord
  require 'csv'
  belongs_to :seed
  belongs_to :user
  has_many :exchanges, dependent: :destroy
  monetize :amount_cents
  self.per_page = 10

  validates :price,
    presence: {
    message: "Pick non validé"
    }
  validates :price,
  numericality: {
    greater_than_or_equal_to: 1
     }

  validates :seed_id, uniqueness: { scope: :user_id }
  scope :newest, -> { order(created_at: :desc)}

  def self.all_with_seed_details
      Pick.select("picks.*, seeds.title as seed_title, seeds.expedition_costs as expedition_costs, users.email as user_email").joins(:seed, :user)
  end

  def self.as_csv
    CSV.generate do |csv|
      columns = %w(seed_title id price expedition_costs state first_name last_name street address_complement zip_code city phone_number user_email)
      csv << columns.map(&:humanize)
      all_with_seed_details.each do |pick|
        csv << pick.attributes.values_at(*columns)
      end
    end
  end

  def mark_exchanges_as_answered
     self.exchanges.not_answered.each do |exchange|
        exchange.admin_review = true
        exchange.save
     end
  end

  def self.my_pick(user, seed)
    where(user_id: user.id, seed_id: seed.id)
  end

  def self.pending_picks(user)
    where(user_id: user, state: "pending")
  end



end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :set_sample, only: [:show, :my_picks, :pick_history]
  after_action :verify_authorized
  skip_after_action :verify_authorized, only: [:my_picks, :pick_history]

  def index
    @user = current_user
    @seed = Seed.friendly.find(params[:seed_id])
    @picks = policy_scope(Pick).where(seed_id: @seed, state: "validated").order(price: :desc )
    #can't export from success campaign as state becomes success
    authorize @picks

    respond_to do |format|
    format.html
    format.csv { send_data @picks.as_csv }
    end

  end

  def show
    @pick = Pick.find(params[:id])
    @user = @pick.user_id
    @seed = @pick.seed
    @exchanges = @pick.exchanges.includes(:user)
    authorize @pick
    unless @pick.state == "pending"
      @customer_infos = @pick.payment
      # @customer_infos = JSON.parse(@pick.payment)["source"]
    end
    @exchange = Exchange.new
  end


  def create
    @seed = Seed.friendly.find(params[:seed_id])
    @my_pick = @seed.picks.new(pick_params)
    @my_pick.user_id = current_user.id
    @user = @my_pick.user_id
    authorize @my_pick
    if @my_pick.save
      @seed.increment_popularity
      respond_to do |format|
        format.html { redirect_to seed_path(@seed) }
        format.js
      end
    end
  end

  def update
    @pick = Pick.find(params[:id])
    @seed = @pick.seed
    authorize @pick
    if @pick.update(pick_params)
      respond_to do |format|
        format.html {redirect_to my_picks_path}
        format.js
      end
    end
  end

  def edit
    @pick = Pick.find(params[:id])
    authorize @pick
    @expedition_costs = @pick.seed.expedition_costs.round(2)
    @campaign_price = @pick.seed.campaign.price.round(2)
  end

  def update_card
    @pick = Pick.find(params[:id])
    authorize @pick
    @campaign = @pick.seed.campaign.id
    @user_id = @pick.user_id
    customer_id = User.find(@pick.user_id).customer_id
    card = params[:stripeToken]
    cu = Stripe::Customer.retrieve(customer_id)
    cu.sources.create(source: card)
    card = Stripe::Token.retrieve(card)["card"]
    cu.default_source = card
    cu.save
    @pick.amount = @pick.seed.campaign.price + @pick.seed.expedition_costs
    begin
      charge = Stripe::Charge.create(
        customer:     customer_id,   # You should store this customer id and re-use it.
        amount:       @pick.amount_cents,
        description:  "Participation au deal pour #{@pick.seed.title} enregistrée",
        currency:     @pick.amount.currency
      )
      @pick.update(payment: card, state: 'finalized', deal_price: charge.to_json)
      CampaignMailer.pick_success(@user_id, @campaign, @pick.id).deliver_later
      redirect_to pick_path(@pick)
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to edit_pick_path(@pick)
    end

  end


  def destroy
    @pick = Pick.find(params[:id])
    authorize @pick
    @seed = @pick.seed
    if @pick.state == "paid"
      payment_string_object = @pick.payment
      payment_hash = JSON.parse(payment_string_object)
      payment_id = payment_hash["id"]
      Stripe::Refund.create(
        charge: payment_id
      )
    end
    @pick.destroy
    @seed.increment_popularity
    respond_to do |format|
      format.html {redirect_to my_picks_path}
      format.js
    end
  end

  def my_picks
    @picks = Pick.pending_picks(current_user).includes(:seed).select {|pick| pick.seed.ongoing?}
  end

  def pick_history
    @picks = current_user.picks.includes(:seed).newest.paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.js { render 'picks/pick_page' }
    end
  end



  private

  def pick_params
    params.require(:pick).permit(:price, :size)
  end


end

app/views/picks/_destroy-pick-modal.html.erb
<div class="pick-modal">
<!-- Modal -->
  <div class="modal fade" id="destroyPick-<%= pick.id%>" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Supprimer votre pick ? </h4>
        </div>
        <div class="modal-body">
          <% if pick.state == "pending" %>
            <h5>Cliquez sur <b>"Supprimer"</b> pour retirer "<%= pick.seed.title %>"" de vos picks, sinon, cliquez sur <b>"Retour"</b>.</h5>
          <% else %>
            <h5>En supprimant votre pick vous annulez votre participation à la campagne d'achat pour obtenir <%= pick.seed.title %>.
            <br>
            <br>Cliquez sur <b>"Supprimer"</b> pour retirer "<%= pick.seed.title %>"" de vos picks, sinon, cliquez sur <b>"Retour"</b>. </h5>
          <% end %>
        </div>
        <div class="modal-footer">
          <div class="action-links">
            <button type="button" id="close-modal-destroy-<%= pick.id%>" class="btn-white" data-dismiss="modal">Retour</button>
            <%= link_to pick_path(pick.id), class: "mid-width  #{'paid' if pick.state == 'paid'}", method: :delete, remote: true do %>
                <div class="btn-orange">Supprimer</div>
              <% end %>
          </div>
          <div class="loader-container hidden"></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/picks/_edit-form.html.erb
<!-- Modal -->
  <div class="modal fade" id="myPick-<%= pick.id%>" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <%= simple_form_for [seed, pick], url: pick_path(pick), remote: true do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><%= pick.seed.title.capitalize %> </h4>
        </div>
        <div class="modal-body">
          <h3 class="edit-pick-title">Modifier votre pick </h3>
          <div class="inputs-and-recap">
            <div class="pick-inputs">
              <div class="price">
                <label for="price">Votre prix</label>
                <%= f.input_field :price, as: :integer, class: 'input-sm form-control edit-pick', id: "#{pick.id}", placeholder: 'Exemple: 150'%>
                <span class="unit">€</span>
              </div>
              <% unless seed.size_guide.blank? %>
                <label for="size" id="size-label">Taille</label>
                <%= f.input_field :size, class: 'input-sm form-control pick', id: 'size-pick', placeholder: "Référez-vous au guide des tailles"%>
              <% end %>
            </div>
            <div class="recap-animation">
              <p>Récap:</p>
              <div class="end-block">
                <div class="how-much">
                  <div>Mon pick:</div>
                  <div class="cout">
                    <div class="counter" id="counter-<%= pick.id %>"><%= pick.price.round(2) %></div>
                    <p>€</p>
                  </div>
                </div>
                <div class="how-much">
                  <div>Livraison:</div>
                  <div class="cout">
                    <div id="cost-input-<%= pick.id %>"><%= seed.expedition_costs.round(2) %></div>
                    <p>€</p>
                  </div>
                </div>
                <div class="how-much">
                  <div class="last-text">Coût total max:</div>
                  <div class="cout">
                    <div class="totalcounter" id="total-counter-<%= pick.id %>"><%= (pick.price + seed.expedition_costs).round(2) %></div>
                    <p id="color-euro">€</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="action-links">
            <button type="button" class="btn-white" data-dismiss="modal" id="close-modal-<%= pick.id%>">Retour</button>
            <%= f.submit "Enregistrer", class: "btn-orange", id: "btn-pick" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/picks/_pick-history.html.erb
<div class="pick-container">
  <%= link_to seed_path(pick.seed) do  %>
    <%= cl_image_tag("#{pick.seed.photos.first.path}", :width=>110, :height=>110, :crop=>"fill", class: "pick-image")%>
  <% end %>
  <div class="pick-body">
    <div class="title-and-delete">
      <%= link_to seed_path(pick.seed) do  %>
          <h3><%= pick.seed.title.capitalize %></h3>
      <% end %>
      <% if pick.seed.ongoing? %>
        <%= link_to "#destroyPick-#{pick.id}", data: {toggle: "modal"} do %>
          <i class="fa fa-times-circle"></i>
        <% end %>
      <% end %>
    </div>
    <div class="price-pick">
      <div class="pick-state">
        <p class="price-display">Pické pour <%= pick.price.round(2) %>€</p>
      <% if pick.seed.ongoing? %>
        <%= link_to "#myPick-#{pick.id}", data: {toggle: "modal"} do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
      <% end %>
      </div>

    </div>
  </div>
</div>


  <% if pick.state == "pending" && pick.seed.ongoing? %>
    <div class="campaign-status pick-pending">
      <div class="seed-infos-timer">
        <div id="timer-<%= pick.id %>" data-timer="<%= pick.seed.expiration %>">
          <%= render "picks/timer", pick: pick  %>
          <div id="clockdiv-<%= pick.id%>" class="clockdiv">
            <div class="dynamic-timer">
              <span class="days"></span>
              <div class="smalltext">j</div>
            </div>
            <div class="dynamic-timer">
              <span class="hours"></span>
              <div class="smalltext">h</div>
            </div>
            <div class="dynamic-timer">
              <span class="minutes"></span>
              <div class="smalltext">m</div>
            </div>
            <div class="dynamic-timer">
              <span class="seconds"></span>
              <div class="smalltext">s</div>
            </div>
          </div>
        </div>
      </div>
      <div class="payment-link">
        <%= link_to new_pick_payment_path(pick) do %>
          <div class="btn-orange">Finaliser pick</div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="pick-other">
      <% case pick.state when "finalized" %>
        <div class= "status-overview">Succès</div>
      <% when "pending" %>
        <div class= "status-overview">Pick expiré</div>
      <% when "campaign_failed" %>
        <div class= "status-overview">Campagne échouée</div>
      <% when "pick_failed" %>
        <div class= "status-overview">Pick échoué</div>
      <% when "campaign_closed" %>
        <div class= "status-overview">Campagne fermée</div>
      <% when "cancelled" %>
        <div class= "status-overview">Campagne annulée</div>
      <% when "refund_failed" %>
        <div class= "status-overview">Erreur</div>
      <% when "error" %>
        <div class= "status-overview">Erreur</div>
      <% when "validated" %>
        <div class= "status-overview">En attente</div>
      <% end %>
      <div class="payment-recap">
        <%= link_to pick_path(pick) do %>
          <div class="btn-white">Détails</div>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/picks/_pick.html.erb
  <% if pick.seed.ongoing? %>
    <%= render "picks/edit-form", seed: pick.seed, pick: pick %>
    <%= render "picks/destroy-pick-modal", pick: pick %>
  <% end %>
  <div class="pick-iterate id-<%= pick.id%>">
    <%= render "picks/pick-history", pick: pick %>
  </div>

app/views/picks/_timer.html.erb
<% content_for(:after_js) do %>

<script>
  function getTimeRemaining(endtime) {
    var t = Date.parse(endtime) - Date.parse(new Date());
    var seconds = Math.floor((t / 1000) % 60);
    var minutes = Math.floor((t / 1000 / 60) % 60);
    var hours = Math.floor((t / (1000 * 60 * 60)) % 24);
    var days = Math.floor(t / (1000 * 60 * 60 * 24));
    return {
      'total': t,
      'days': days,
      'hours': hours,
      'minutes': minutes,
      'seconds': seconds
    };
  }
  function initializeClock(id, endtime) {
    var clock = document.getElementById(id);
    var daysSpan = clock.querySelector('.days');
    var hoursSpan = clock.querySelector('.hours');
    var minutesSpan = clock.querySelector('.minutes');
    var secondsSpan = clock.querySelector('.seconds');
    function updateClock() {
      var t = getTimeRemaining(endtime);
      daysSpan.innerHTML = t.days;
      hoursSpan.innerHTML = ('0' + t.hours).slice(-2);
      minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);
      secondsSpan.innerHTML = ('0' + t.seconds).slice(-2);
      if (t.total <= 0) {
        clearInterval(timeinterval);
        // document.getElementById("demo").innerHTML = "EXPIRED";
        // Ajax request to render either the show or the result page
        $.ajax({
          type: "GET",
          url: "<%= pick_history_path %>",
          dataType: 'script'
        });
      }
    }
    updateClock();
    var timeinterval = setInterval(updateClock, 1000);
  }
  var seeddue = $('#timer-<%= pick.id%>').data('timer')
  var deadline = new Date(Date.parse(seeddue.replace(/-/g, '/')));
  initializeClock('clockdiv-<%= pick.id%>', deadline);
  </script>
<% end %>

app/views/picks/_update_address.html.erb
<h3>Livraison</h3>
<div class="address-input"><%= pick.full_name %></div>
<div class="address-input"><%= pick.street %></div>
<div class="address-input"><%= pick.zip_code %> <%= pick.city %></div>
<% unless pick.address_complement.blank? %>
  <div class="address-input"><%= pick.address_complement %></div>
<% end %>
<% unless  pick.phone_number.blank? %>
  <div class="address-input"><%= pick.phone_number %></div>
<% end %>

app/views/picks/create.js.erb
$(document).ready(function(){
  $("#close-modal").click();
  $(".pick-section").html('<%= j render 'seeds/pick-section', my_pick: @my_pick %>');
  $(".pick-container-xs").html('<%= j render 'seeds/pick-section-xs', my_pick: @my_pick %>');
  $(".my-picks").html('<%= j render 'shared/pending-picks' %> ');
  $(".complete-link").toggleClass("shake");
  $(".btn-blue").click();
})

app/views/picks/destroy.js.erb
$(document).ready(function(){
  $("#close-modal-destroy-<%= @pick.id%>").click();
  $(".pick-iterate.id-<%=@pick.id%>").slideUp();
  $(".action-links").removeClass("hidden");
  $(".loader-container").addClass("hidden").html("");
  $(".my-picks").html('<%= j render 'shared/pending-picks' %> ');

})

app/views/picks/edit.html.erb
 <script src="https://js.stripe.com/v3/"></script>
<div class="paiement-container">
   <div class="booking-confirmation">
    <h2>Erreur lors du paiement</h2>
    <div class="recap-and-pay">
      <div class="recap">
        <h3>Récap</h3>
        <div class="explanation">
          <div class="image-title-price">
            <%= cl_image_tag @pick.seed.photos.first.path, :height=>75, :crop=>"scale" %>
            <div class="recap-paragraph">
              <div>
              <h4><%= @pick.seed.title %></h4>
              <p>Prix original: <%= @pick.seed.price %> €</p>
              </div>
              Pické le: <%= @pick.created_at.strftime("%d/%m/%Y") %> pour <%= @pick.price %> €
            </div>
          </div>
          <div class="how-much">
            <div class="text">Prix négocié :</div>
            <p class="price"><%= @campaign_price %> €</p>
          </div>
          <div class="how-much">
            <div class="text">Coût livraison:</div>
            <p class="price"><%= @expedition_costs %></p>
          </div>
          <div class="how-much last">
            <div class="text"><b>A payer:</b></div>
            <p class="price"><%= (@campaign_price + @expedition_costs).round(2)  %> €</p>
          </div>
        </div>
      </div>
      <div class="stripe-card-form">
        <div class="info-detail">La campagne est un succès et vous avez obtenu <%= @pick.seed.title %> pour <%= @campaign_price %> €. Cependant, la carte enregistrée lors de votre confirmation de participation ne peut être débitée. Merci de mettre à jour cette carte afin que nous puissions procéder au débit.
        </div>
        <div class="user-update-form">
        <%= form_tag update_card_pick_path(@pick), id: "payment-form" , method: :patch do %>
          <div class="form-row">
            <label for="card-element">
              Carte bancaire
            </label>
            <div id="card-element">
              <!-- A Stripe Element will be inserted here. -->
            </div>

            <!-- Used to display form errors. -->
            <div id="card-errors" role="alert"></div>
          </div>
          <div class="cgu-reminder"></div>
          <button class="booking-button btn-orange" id="validate-paiement">
            <i class="fa fa-lock"></i>
            <p>Payer <%= (@campaign_price + @expedition_costs).round(2) %> €</p>
          </button>
        <% end %>
      </div>
      <div class="loader-container hidden">
      </div>
    </div>
   </div>
  </div>
</div>

<%= render "shared/stripe-form" %>

app/views/picks/my_picks.html.erb
<%= render 'shared/sub-navbar' %>
<div class="page-container">
  <div class="pick-feed">
    <%if @picks.any? %>
      <div class="pick-presentation">
        <h2>Vos picks</h2>
        <div class="pending-and-all">
          <div class="pick-menu left-menu" id="selected-menu">A valider</div>
          <%= link_to pick_history_path do%>
            <div class="pick-menu right-menu">Historique</div>
          <% end %>
        </div>
        <% @picks.each do |pick| %>
          <% if pick.seed.ongoing? %>
            <%= render "picks/edit-form", seed: pick.seed, pick: pick %>
            <%= render "picks/destroy-pick-modal", pick: pick %>
          <% end %>
          <div class="pick-iterate id-<%= pick.id%>">
          <%= render "picks/pick-history", pick: pick %>
          </div>
        <% end %>
      </div>
      <% else %>
        <div class="pick-feed">
          <div class="pick-presentation">
            <h2>Vos picks</h2>
            <div class="pending-and-all">
              <div class="pick-menu left-menu" id="selected-menu-bis">A valider</div>
              <%= link_to pick_history_path do%>
                <div class="pick-menu right-menu">Historique</div>
              <% end %>
            </div>
            <p class="no-picks-yet">Pas de picks à finaliser</p>

          </div>
        </div>

    <% end %>

  </div>
</div>

app/views/picks/pick_history.html.erb
<%= render 'shared/sub-navbar' %>
<div class="page-container">
  <div class="pick-feed">
    <%if @picks.any? %>
      <div class="pick-presentation">
        <h2>Vos picks</h2>
        <div class="pending-and-all">
          <%= link_to my_picks_path do %>
            <div class="pick-menu left-menu">A valider</div>
          <% end %>
          <div class="pick-menu right-menu" id="selected-menu">Historique</div>
        </div>
        <div class="pick-infinite">
          <div id="infinite-scrolling">
            <%= will_paginate @picks %>
          </div>
          <%= render @picks %>
        </div>
      </div>
      <% else %>
        <div class="pick-feed">
          <div class="pick-presentation">
            <h2>Vos picks</h2>
            <div class="pending-and-all">
              <%= link_to my_picks_path do %>
                <div class="pick-menu left-menu">A valider</div>
              <% end %>
              <div class="pick-menu right-menu" id="selected-menu-bis">Historique</div>
            </div>
            <p class="no-picks-yet">Vous n'avez encore rien pické jusqu'à présent</p>

            <div class="index-path">
              <%= link_to seeds_path do %>
                <div class="btn-orange">Y remédier</div>
              <% end %>
            </div>

          </div>
        </div>

    <% end %>

  </div>
</div>

app/views/picks/show.html.erb
<div class="sub-container hidden-xs">
  <div class="sub-nav">
    <%= link_to seeds_path do %>
      <div class="cat selected">
        <div class="filter-icon glyphicon glyphicon-globe"></div>
        <p>Tous</p>
      </div>
    <% end %>
    <%= link_to popular_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-fire"></div>
        <p>Tendances</p>
      </div>
    <% end %>
    <%= link_to newest_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-leaf"></div>
        <p>Récents</p>
      </div>
    <% end %>
    <%= link_to last_day_path do %>
      <div class="cat">
        <div class="filter-icon glyphicon glyphicon-flash"></div>
        <p>Dernier jour</p>
      </div>
    <% end %>
    <%= link_to seed_path(@sample) do %>
    <div class="cat">
      <div class="filter-icon glyphicon glyphicon-random"></div>
      <p>Hasard</p>
    </div>
    <% end %>
  </div>
</div>


<div class="pick-details-container">
  <div class="recap">
    <h3>Récap</h3>
    <div class="explanation">
      <div class="image-title-price">
        <%= cl_image_tag @seed.photos.first.path, :height=>75, :crop=>"scale" %>
        <div class="recap-paragraph">
          <div>
          <h4><%= @seed.title %></h4>
          <p>Pické le: <%= @pick.created_at.strftime("%d/%m/%Y") %>
            <% if @pick.state == "finalized" %>
              <br><b>Mon pick: <%= (@pick.price).round(2) %> €</b>
            <% end %>
          </p>
          </div>
        </div>
      </div>
      <div class="how-much">
        <div class="text">Coût livraison:</div>
        <p class="price"><%= (@seed.expedition_costs).round(2) %> €</p>
      </div>
      <div class="how-much">
        <% if @pick.state == "finalized" %>
          <div class="text">Prix négocié:</div>
          <p class="price"><%= @pick.seed.campaign.price.round(2) %> €</p>
        <% else %>
          <div class="text">Pické pour:</div>
          <p class="price"><%= (@pick.price).round(2) %> €</p>
        <% end %>
      </div>
      <div class="how-much last">
        <% if @pick.state == "finalized" %>
          <div class="text"><b>Coût total:</b></div>
          <p class="price"><%= (@pick.seed.campaign.price.round(2) + @seed.expedition_costs).round(2) %> €</p>
        <% else %>
          <div class="text"><b>Coût total max:</b></div>
          <p class="price"><%= (@pick.price + @seed.expedition_costs).round(2) %> €</p>
        <% end %>
      </div>
      <div class="info-detail"><%= render 'picks/pick-status', pick: @pick %>
      </div>
      <% if @customer_infos %>
        <div class="ship-and-payment">
          <div class="item ship">
            <%= render 'picks/show_address', pick: @pick  %>
          </div>
          <div class="item payment">
            <h5>Paiement</h5>
            <div class="card-input"><%= @customer_infos["brand"]%></div>
            <div class="card-input card-numbers">
              **** **** **** <%= @customer_infos["last4"] %>
            </div>
            <div class="card-input">
              <%= @customer_infos["exp_month"]%>/<%= @customer_infos["exp_year"] %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="exchanges-and-questions">
    <div class="exchange-header">
      <%= image_tag "speech-bubble.png", class:"speech-img" %>
      <p>Une question ?</p>
    </div>
        <div id="exchanges">
          <div class="all-messages">
            <% unless @exchanges.blank? %>
            <% @exchanges.each do |exchange| %>
              <div class="message-block <%= exchange.message_author %>">
              <div class="avatar-author-date">
                <%if exchange.user.photo? %>
                  <%= cl_image_tag exchange.user.photo.path, class: "pic"%>
                <% else %>
                  <i class="fa fa-user author-avatar"></i>
                <% end %>
                <div class="author-and-date">
                  <div class="message-sent"><%= exchange.created_at.strftime("%d/%m/%Y") %>
                  </div>
                  <div class="user-pseudo">
                    <%= exchange.user.pseudo %>:
                  </div>
                </div>
              </div>
              <div class="question-content">
                <%= simple_format(exchange.question) %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div id="exchange_form">
      <%= render 'exchanges/form', pick: @pick, exchange: @exchange %>
    </div>

    <% if current_user.admin == true && @pick.exchanges.any? %>
      <div class="validate-link">
        <p>Toutes les questions client ont trouvé une réponse?</p>
        <%= link_to exchange_path(@pick.exchanges.last), :method => :patch do%>
          <div class="btn-blue">Oui</div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>
<%= render 'shared/footer' %>

app/views/picks/update.js.erb
$(document).ready(function(){
  $("#close-modal-<%= @pick.id%>").click();
  $(".pick-iterate.id-<%= @pick.id%>").html('<%= j render 'picks/pick-history', pick: @pick %>');

})